### PR TITLE
Dev/search

### PR DESCRIPTION
**Pull request by igrowsquareroots**

### CODE REVIEW

**Comment by lynguyen11** [comment]
Can you point to the url of the resources of this on the material-ui.com
site?

Thanks.
Mr. Nguyen

**Comment by mbacvanski** [comment]
https://material-ui-next.com/demos/lists/

**Comment by igrowsquareroots** [comment]
I added material-ui

**Comment by lynguyen11** [comment]
When I  do a search, my phone auto capitalize the first letter, and the
search doesn't work. We should fix that ASAP.
I will work on expanding the search list database over the break.

Best
Mr Nguyen

On Nov 20, 2017 10:11 PM, "Marc Bacvanski" <notifications@github.com> wrote:

Merged #35 <https://github.com/mvhs-apps/mvhs-app-pwa/pull/35>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mvhs-apps/mvhs-app-pwa/pull/35#event-1351315886>, or mute
the thread

**Pull request merged**
