### PR TITLE
ASB Calendar

### PR DESCRIPTION
**Pull request by AlexJVG**
This is the old ASB calendar page. I will be making the new version soon.

### CODE REVIEW

**Comment by mbacvanski** [comment]
It looks really good! We need to add some title text or something that says that that tab is for ASB though. Perhaps like how we do on the About page 

image

We could add titles above the date picker in all the other tabs.

**Comment by lynguyen11** [comment]
For now, lets not push hat to master yet.  Alex will be working on the a
drop down menu on the calendar page in the new version, and the ASB  events
will be integrated into that.  In the end, we will have just 3 tabs .  One
tab for just calendar events, maps, and then the about page.

Best,
Mr. Nguyen

**Comment by lynguyen11** [comment]
On second thought, I am starting to like having a second tab for the school
calendar events.  It is faster to move to a tab then to scroll down to see
the events.  Can we have both the school and calendar events on a separate
tab with the drop down menu to select a calendar?

Best,
Mr. Nguyen

**Comment by lynguyen11** [comment]
so one tab for bell schedule, one for calendar events (drop down menu for
other calendars but our school will be the default), one for map, and one
for the about page.  can that work?

**Comment by plusCubed** [comment]
I think the unified page is better, as it relates everything with the date picker on one page. We can change it so it's a two-column layout on desktop, so it's a better use of space.

**Pull request merged**
